In [1]:
%%capture
!pip install numpy

In [3]:
import numpy as np 


In [5]:
arr = np.array([1,2,3])
print(arr)
print("Data Type:",arr.dtype) 

[1 2 3]
Data Type: int32


In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [9]:
arr = np.array([10, 20, 30, 40, 50])

# Access elements by index
print("First Element:", arr[0])
print("Last Element:", arr[-1])

# Slicing
print("First Three Elements:", arr[:3])
print("Elements from Index 2 to 4:", arr[2:5])


First Element: 10
Last Element: 50
First Three Elements: [10 20 30]
Elements from Index 2 to 4: [30 40 50]


In [11]:
arr = np.array([1, 2, 3])
print("Array + 10:", arr + 10)

Array + 10: [11 12 13]


In [13]:
arr = np.array(range(1,11))
a / 2 

array([0.5, 1. , 1.5])

In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise multiplication
print("Element-wise Multiplication:\n", A * B)

# Matrix multiplication (dot product)
print("Matrix Multiplication:\n", np.dot(A, B))

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
